version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: planora
      POSTGRES_USER: planora_user
      POSTGRES_PASSWORD: secretpass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ghcr.io/lesstray/planora:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: planora
      DB_USER: planora_user
      DB_PASSWORD: secretpass
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  pg_data:
