# Generated by Django 3.2.25 on 2025-06-08 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default=str, max_length=255, verbose_name='Роль (преподаватель/студент)'),
            preserve_default=False,
        ),
    ]
