# Generated by Django 3.2.25 on 2025-06-08 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studygroup_subject'),
        ('registration', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='home.studygroup', verbose_name='Учебная группа студента'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_subjects',
            field=models.ManyToManyField(blank=True, related_name='students', to='home.Subject', verbose_name='Предметы студента'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'teacher'}, related_name='student_of', to=settings.AUTH_USER_MODEL, verbose_name='Препеподаватели студента'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teaching_groups',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='home.StudyGroup', verbose_name='Группы преподавания'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teaching_subjects',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='home.Subject', verbose_name='Преподаваемые предметы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент')], max_length=10, verbose_name='Роль'),
        ),
    ]
