# Generated by Django 3.2.25 on 2025-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_studygroup_subject'),
        ('registration', '0002_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='home.Subject', verbose_name='Преподаваемые предметы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, to='home.StudyGroup', verbose_name='Учебные группы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('teacher', 'Преподаватель'), ('student', 'Студент')], max_length=10, verbose_name='Роль'),
        ),
    ]
