"""
Django settings for planora project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import subprocess
from pathlib import Path
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Разрешенные хосты
ALLOWED_HOSTS = []

# Определение приложений
INSTALLED_APPS = [
    'rest_framework',
    'drf_yasg',
    'django_recaptcha',
    'django_extensions',
    'django.contrib.admin',
    'django_prometheus',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'django_otp',
    'django_otp.plugins.otp_email',
    'two_factor',
    'registration',
    'login',
    'home',
    'about',
    'account',
    'statistic',
]

# Определение промежуточного слоя
MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'account.middleware.SessionInfoMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

# Валидация пароля
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Корневой конфиг urls
ROOT_URLCONF = 'planora.urls'
WSGI_APPLICATION = 'planora.wsgi.application'

# Локализация
LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Шаблоны
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Модель пользователя
AUTH_USER_MODEL = 'registration.CustomUser'

# Путь до статики
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# PK по умолчанию
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Настройки базовых URL
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

# Загрузка переменных окружения
load_dotenv(BASE_DIR / '.env')

# Настройка проекта PLANORA
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'

# Настройка сессии
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_AGE = 86400  # 1 день в секундах

# Настройка БД
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASS'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
    }
}

# Настройка электронной почты
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = 465
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Настройка ReCAPTCHA
RECAPTCHA_PUBLIC_KEY = str(os.getenv('RECAPTCHA_PUBLIC'))
RECAPTCHA_PRIVATE_KEY = str(os.getenv('RECAPTCHA_PRIVATE'))

# Настройка OAuth2 with Google
SOCIAL_AUTH_URL_NAMESPACE = 'social'
AUTHENTICATION_BACKENDS = (
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.getenv('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
    'openid'
]
# Если одно и то же письмо пытаются залогинить через разные провайдеры —
# объединит их в один User
SOCIAL_AUTH_ASSOCIATE_BY_EMAIL = True

# Не позволит создать два User с одним и тем же email,
# если выше шаг не сработал (по умолчанию False)
SOCIAL_AUTH_UNIQUE_EMAIL = True

# Если заходят с OAuth‑аккаунтом, который уже привязан — перезальёт данные
# (например, обновит first_name/last_name)
SOCIAL_AUTH_CLEAN_USER_DATA = True
SOCIAL_AUTH_PIPELINE = (
    # 1. Берет из ответа провайдера базовую инфу (имя, email и т.п.)
    'social_core.pipeline.social_auth.social_details',

    # 2. Получает уникальный id провайдера
    'social_core.pipeline.social_auth.social_uid',

    # 3. Проверяет, разрешено ли логиниться через этого провайдера
    'social_core.pipeline.social_auth.auth_allowed',

    # 4. Ищет уже привязанный аккаунт
    'social_core.pipeline.social_auth.social_user',

    # 5. Блокировка преподавателей (по домену)
    'complete_profile.pipeline.block_teachers_by_domain',
    
    # 6. Генерирует username (если его нет)
    'social_core.pipeline.user.get_username',

    # 7. Если пользователь с таким email уже есть - сразу связывает с ним
    'social_core.pipeline.social_auth.associate_by_email',

    # 8. Если все еще не нашёлся пользователь - создает нового
    'social_core.pipeline.user.create_user',

    # 9. Ассоциирует Social Auth запись с объектом User
    'social_core.pipeline.social_auth.associate_user',

    # 10. Сохраняет токены/другие данные из ответа провайдера
    'social_core.pipeline.social_auth.load_extra_data',

    # 11. Обновляет детали пользователя (first_name, last_name, email)
    'social_core.pipeline.user.user_details',

    # 12. Если новый студент - запрос ФИО и группы
    'complete_profile.pipeline.require_additional_info'
)

# Путь к корню репозитория вручную (на один уровень выше BASE_DIR)
REPO_ROOT = BASE_DIR.parent
VERSION_FILE = REPO_ROOT / 'version.txt'

# Получение версии
try:
    # Получаем короткий хеш коммита, указывая путь к корню репозитория
    version = subprocess.check_output(
        ['git', '-C', str(REPO_ROOT), 'rev-parse', '--short', 'HEAD'],
        stderr=subprocess.DEVNULL
    ).decode().strip()

    # Записываем в файл version.txt
    VERSION_FILE.write_text(version)
except Exception:
    version = 'unknown'
print(version)
print(REPO_ROOT)
GIT_VERSION = version
