# Generated by Django 3.2.25 on 2025-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu', models.FloatField()),
                ('ram', models.FloatField()),
                ('gpu', models.FloatField()),
                ('disk', models.JSONField()),
            ],
        ),
    ]
