# Generated by Django 4.2.20 on 2025-06-08 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentplan',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='studentplan',
            name='student',
        ),
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='schedule_url',
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='AttendanceStats',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='StudentPlan',
        ),
    ]
