# Generated by Django 3.2.25 on 2025-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='twofactorcode',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
